<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PLC_PRG" Id="{cf366734-d49e-4bbc-8306-bebddd2306df}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PLC_PRG
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_Cell();

RETURN;]]></ST>
    </Implementation>
    <LineIds Name="PLC_PRG">
      <LineId Id="5" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>